[tool.black]
   line-length = 95
   target-version = ['py39']
   include = '\.pyi?$'
   extend-exclude = '''
   /(
     # directories
     \.eggs
     | \.git
     | \.hg
     | \.mypy_cache
     | \.tox
     | \.venv
     | build
     | dist
   )/
   '''

   [tool.isort]
   profile = "black"
   line_length = 95
   multi_line_output = 3
   include_trailing_comma = true
   force_grid_wrap = 0
   use_parentheses = true
   ensure_newline_before_comments = true

   [tool.mypy]
   python_version = "3.9"
   warn_return_any = true
   warn_unused_configs = true
   ignore_missing_imports = true
